name: N1-OpenWrt-23.05

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - N1-OpenWrt-23.05

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Show system
      run: |
        echo -e "💬 Server information \n"
        echo -e "💻 Server running on Ubuntu: [ Release: $(cat /etc/os-release | grep VERSION_CODENAME | cut -d '=' -f2) / Host: $(arch) ] \n"
        echo -e "🧮 Server CPU configuration information: \n$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo -e "💾 Server memory usage: \n$(free -h) \n"
        echo -e "🗃️ Server space usag: \n$(df -hT ${GITHUB_WORKSPACE}) \n"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
        sudo -E apt-get -y update
        sudo -E apt-get -y purge azure-cli* ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -y install aria2
        sudo -E wget -P /usr/local/sbin/ https://github.com/HiGarfield/lede-17.01.4-Mod/raw/master/.github/backup/apt-fast
        sudo -E chmod -R 755 /usr/local/sbin/apt-fast
        sudo -E apt-fast -y -qq install dwarves quilt llvm clang lldb lld build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev \
          patch python2.7 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib p7zip-full msmtp libssl-dev texinfo libreadline-dev \
          libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget ccache curl \
          swig coreutils vim nano python3 python3-dev python3-pip python3-ply python3-pyelftools lrzsz scons
        pip3 install --user -U pylibfdt
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo timedatectl set-timezone "$TZ"
        echo "status=success" >> ${GITHUB_OUTPUT}

    - name: Prepare source code
      run: |
        sudo chown -R runner:runner /home/runner/work/build_openwrt
        cp -r scripts/openwrt-23.05/. ./
        /bin/bash 01_prepare_source_code.sh
        echo "build_date=$(date +%Y.%m.%d)" >> ${GITHUB_ENV}

    - name: Prepare package
      run: |
        cd openwrt
        cp -r ../scripts/openwrt-23.05/. ./
        /bin/bash 02_prepare_package.sh

    - name: Convert Translation
      run: |
        cd openwrt
        /bin/bash 03_convert_translation.sh

    - name: Demote Iptables
      run: |
        cd openwrt
        /bin/bash 04_demote_iptables.sh

    - name: Add ACL
      run: |
        cd openwrt
        /bin/bash 05_create_acl_for_luci.sh -a

    - name: Load custom configuration
      run: |
        latest_release="$(curl -s https://github.com/openwrt/openwrt/tags | grep -Eo "v[0-9\.]+-*r*c*[0-9]*.tar.gz" | sed -n '/23.05/p' | sed -n 1p | sed 's/.tar.gz//g' | sed 's/v//g')"
        cp -rf patch/files openwrt/files && cp -r patch/openwrt-23.05/. openwrt/files/
        sed -i -e "s,DATE,${{ env.build_date }}," -e "s,WRT_VERSION,OpenWrt ${latest_release}," ./openwrt/files/etc/banner
        sed -i "s,OPENWRT_VER,${latest_release}," ./openwrt/package/new/addition-trans-zh/files/zzz-default-settings
        echo "latest_release=${latest_release}" >> ${GITHUB_ENV}

    - name: Make config
      run: |
        cd openwrt
        cp ../config/openwrt-23.05/config.seed .config
        make defconfig

    - name: Download package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      continue-on-error: true
      run: |
        cd openwrt
        make -j$(($(nproc) + 1))

    - name: If error
      if: steps.compile.outcome == 'failure'
      run: |
        cd openwrt && make -j1 V=s

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt_rootfs_${{ env.build_date }}
        path: openwrt/bin

    - name: Package firmware
      uses: ffuqiangg/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/*/*/*rootfs.tar.gz
        openwrt_board: s905d
        kernel_repo: ophub/kernel
        openwrt_kernel: 5.15.148
        kernel_usage: flippy
        auto_kernel: true
        image_name: N1-OpenWrt-${{ env.latest_release }}-${{ env.build_date }}

    - name: Upload firmware to release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag: ${{ env.build_date }}
        allowUpdates: true
        replacesArtifacts: true
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/N1-OpenWrt-${{ env.latest_release }}-${{ env.build_date }}.zip

    - name: telegram notification
      if: github.event_name == 'repository_dispatch'
      run: |
        MSG="
        *OpenWrt ${{ env.latest_release }}* 编译完成
        [N1-OpenWrt-${{ env.latest_release }}-${{ env.build_date }}.zip](https://github.com/ffuqiangg/build\_openwrt/releases/download/${{ env.build_date }}/N1-OpenWrt-${{ env.latest_release }}-${{ env.build_date }}.zip)
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_TO }}&text=${MSG}&parse_mode=MarkDown&disable_web_page_preview=true"
